### ISSUE TITLE
Something wrong with Cocoapod configuration

### ISSUE THREAD

**Issue by grahamburgsma** [52inc/Pulley#103]
Something with the pod configuration is causing a warning on `pod install`. It has been like this for a few months, so it isn't a new problem.

It can be reproduced by creating a new project, and adding Pulley as a pod. On `pod install` the warning below will show. Note no other pod causes this problem, I have added others such as Alamofire, Kingfisher, ObjectMapper etc. and none of them cause this warning, it only happens when `Pulley` is added.

```
[!] The `test [Debug]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-test/Pods-test.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `test [Release]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-test/Pods-test.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

Would be nice to see this warning go away! Great library though, thanks for making.

**Comment by brendan09** [comment]
So, this isn’t actually a problem or an issue. This is Pulley implementing something that other pods _should_ be implementing to be spec compliant. However, many don’t.

This is caused by including the swift version dot file, which tells the swift compiler the exact version of Swift Pulley is expecting to be compiled by. This allows people to use the Swift 4.0 version of Pulley in projects using Swift 3.2 or Swift 4.0.1, because we identify Pulley’s “correct” version to the compiler.

It does issue a warning because the frameworks Swift Version is specified, not inherited. But, it does allow for compatibility with more projects. Other pods just rely on expecting the developer to understand / manage only using compatible pods by hand, Pulley uses the appropriate pod configuration to handle it automatically.

**Comment by grahamburgsma** [comment]
Thanks for the detailed explanation!
I will close this issue.
