### ISSUE TITLE
Drawer Position

### ISSUE THREAD

**Issue by alexjessecole** [52inc/Pulley#112]
Is it possible to change the orientation of the drawer? Like for example is it possible to have the drawer at the top of the view and pull down?

**Comment by brendan09** [comment]
Although not officially supported, you could use UIView's CGAffineTransform to rotate it upside down. It should work ok, but I'm not sure what the consequences will be with regards to safe areas.

You'll need to apply the same 'upside down' transform to your drawer and main content view controller's views as well so that they appear right-side up.

**Comment by brendan09** [comment]
@alexjessecole The master branch now includes support for this, in the form of mimicking the iPad Maps layout. You can customize Pulley's settings to be full-width (and still pull down from top), if you'd like.

Right now it's more of a 'test' version, as it required a lot of changes. If you feel like giving it a try, I'm looking for feedback / bug-testing before pushing it out to CocoaPods.

**Comment by brendan09** [comment]
Just dropping a quick note before I close this issue:

Version 2.2.0 is now up on CocoaPods, if you'd like to use it, and includes iPad support (side panel, pull from top). You may need to 'pod repo update' before running 'pod update Pulley' in order to get it.
