### ISSUE TITLE
PulleyDrawerViewControllerDelegate Flexibility

### ISSUE THREAD

**Issue by CareerFairPlus** [52inc/Pulley#113]
First off, thank you for the great library and the great support!

In the project that I'm working on I've run into a situation where I would like something _other_ than the `drawerContentViewController` to implement the `PulleyDrawerViewControllerDelegate` interface.  Is there any reason, other than it being handy in most cases, to not have a separate `drawerViewControllerDelegate` param in `PulleyViewController`?

**Comment by brendan09** [comment]
This was done because the drawerViewController should be responsible for the available presentation states (from an overall architecture point of view).

If you would like another object to be in charge of this, then you can implement the appropriate delegate methods in your drawerContentViewController and forward the delegate calls on to the object that you'd like to receive them.

**Comment by CareerFairPlus** [comment]
Ok, I can see the benefit of tying those two things together, especially for recalculating drawer positions when the VC is updated.

The issue I was having is that the VC that I want to use as the drawer content VC is an existing VC that is written in Objective-C.  I really really don't want to re-write it.  I had written another class that would "bridge" the delegate calls between Pulley and ObjC-safe versions of the calls that could be implemented by the existing VC without needing to change Pulley in any way, but that would require me to set the bridge class as the `PulleyDrawerViewControllerDelegate`.

It sounds like my only real option is to write a VC in Swift that can live as the drawer VC and handle those events and then have it display this other VC as a container.

Thanks for elaborating!
