### ISSUE TITLE
Different values for collapsedDrawerHeight and partialRevealDrawerHeight

### ISSUE THREAD

**Issue by jMelvins** [52inc/Pulley#120]
Hello there, thank you for your great library but there is an issue here. I used your DemoApp and found it.
For example, I have a two different states for drawerContent: 
the first one should have the collapsedDrawerHeight = 68 and the partialRevealDrawerHeight = 264,
the second one - collapsedDrawerHeight = 130, partialRevealDrawerHeight = 130 too.
Primary content in this case should be the same for each of states. When I try to change this values like in the first pic, I have an issue like in the second pic: representing of the drawerContent didn't change. Note: if i will uncomment 131 and 135 lines there isn't issue at all.

![2017-11-15 5 26 10](https://user-images.githubusercontent.com/24705601/32840961-39e66bbe-ca2a-11e7-8a3d-6351985c26fa.png)
![simulator screen shot - iphone 8 plus - 2017-11-15 at 17 27 40](https://user-images.githubusercontent.com/24705601/32840996-50142a5c-ca2a-11e7-96c6-ce7fb199fdd1.png)

**Comment by brendan09** [comment]
Definitely looks like a bug. After those lines, try calling setDrawerPosition on Pulley. (Pass it the current drawer position if you need to). It may provide a workaround until this is fixed.

Are you using the version on CocoaPods?

**Comment by jMelvins** [comment]
I called setDrawerPosition in the 133 line. Or do you mean something else?
Yes, I'm using version on CocoaPods.

**Comment by brendan09** [comment]
Apologies, I read your issue the wrong way. It looks like there’s a bug when set drawer position is called. Still a bug, just a slightly different one.

For now you may have to set the primary view controller after setting your drawer position (even if you set it to the current VC you’re already using). You can do that by setting it to drawer.primaryContentViewController (rather than pulling a new instance from the Storyboard).

I’ll try to get a fix out as soon as possible. Let me know if that doesn’t work as a workaround and I’ll see what I can come up with.

**Comment by jMelvins** [comment]
Yeah, it helped me, thank you for a quick response!
