### ISSUE TITLE
Keep dragging content to close drawer

### ISSUE THREAD

**Issue by CodeStage** [52inc/Pulley#124]
How would you go about implementing the exact behaviour like in the maps app, where you can keep dragging the drawer's content without letting go and touching again to close the drawer?

Assuming you have a table view in the drawer and have scrolled the content a bit. I want to be able to continue dragging after the content has reached offset 0 to drag the drawer.

**Comment by brendan09** [comment]
There's a conversation about this here: https://github.com/52inc/Pulley/issues/97

Essentially: This requires deeper integration with the gesture recognizers in UITableView / UIScrollView than what I believe is publicly available. I would love to be proved wrong on that. But, at a minimum, because it involves the drawer content view controller's implementation, it's out of scope for Pulley itself.

**Comment by CodeStage** [comment]
Thanks, that's what I thought. A different approach would be required to achieve this.
