### ISSUE TITLE
Pulley must be the root VC

### ISSUE THREAD

**Issue by matteodem2** [52inc/Pulley#126]
Hello,
I think this is not an issue but a different behaviour I wish to have for this component.
In my app, a bottom sheet can be displayed with an action, otherwise no bottom sheet is needed on screen.
To do so, when I need to display a bottom sheet, I want to create Pulley passing my main view controller as content view, the drawer view controller, and adding it as a child view controller for my main view controller.
I tried this but I get a EXC_BAD_ACCESS.

I think that Pulley run only as the root view controller.

Is this true ?

**Comment by brendan09** [comment]
Pulley doesn’t have to be the root view controller. However, you can’t use an view controller that’s already in the window’s presentation hierarchy as the main content view controller or drawer view controller. This is a restriction from UIKit, because you’d be trying to present a view controller from a view controller that had been removed from the window presentation hierarchy. When you assign a view controller for the main content to Pulley, it necessarily removes it from the window and adds it as a sub view Pulley can manage.

This is a restriction for any view controller containing child view controllers, not just Pulley.

To accomplish your goal, I would use Pulley as the root view controller and set the drawer state to “closed”. When you’re ready to show the drawer, assign the new drawer view controller and then change the position to “collapsed” so that the drawer appears.

**Comment by matteodem2** [comment]
Thanks Brendan for your answer, I understand better knowing that Pulley remove the content from window and add it as his subview, In practice, Pulley must be used as root but I can't do it with my architecture.
I need to add the bottom sheet as a child VC of content VC and  I will implement the gesture behaviour.
