### ISSUE TITLE
Several errors during buildtime

### ISSUE THREAD

**Issue by thewriterl** [52inc/Pulley#131]
<img width="256" alt="git" src="https://user-images.githubusercontent.com/19268248/33460635-ee393dbe-d626-11e7-9e2c-d8be3ee20cdc.png">

got the Demo files on a new project for it be able to run on my iPhone but the code has some errors like 'PulleyViewController has no member currentDisplayMode' which don't make sense to me.

btw, I did install the pod.

thanks

**Comment by brendan09** [comment]
The code / sample project on master is currently in development / beta. It has API and protocol changes present that are _not_ in the most recent official release on Cocoapods. You're seeing errors as a result of this.

The most recent release is here: https://github.com/52inc/Pulley/releases/tag/2.1.0

Download the zip file of that and use it's files in your project so that it's compatible with the CocoaPods version of the library you're using.

Let me know if you have any questions!

**Comment by brendan09** [comment]
Just dropping a quick note before I close this issue:

Version 2.2.0 is now up on CocoaPods, if you'd like to use it. You may need to 'pod repo update' before running 'pod update Pulley' in order to get it.
