### ISSUE TITLE
Constraint Error Zero Width

### ISSUE THREAD

**Issue by GrantJEmerson** [52inc/Pulley#142]
Hi,
    I am getting an autolayout issue in which the DrawerContentContainer's width is 0. This is the error: "<NSAutoresizingMaskLayoutConstraint:0x600000285cd0 h=--& v=--& UIView:0x7f804d42da90.width == 0   (active)>". Is there any way to fix this?

**Comment by brendan09** [comment]
The initial layout frame before added to the window (and a layout pass is run) is CGSize.zero. If you force a layout pass (layoutIfNeeded or setNeedsLayout) before Pulley is added to the window's hierarchy, you'll see that error if you have constraints that are incompatible with a zero frame.

It's recommended not to use layoutIfNeeded or setNeedsLayout during viewDidLoad, as that's usually the underlying source of the issue.

If that doesn't apply to you, or you aren't sure what could be triggering a layout pass before Pulley is added to the window, please follow-up with some additional information on how you're using Pulley:

• Is PulleyViewController the rootViewController of the window?
• How are you creating PulleyViewController?
• Is your drawer view controller from Interface Builder, or created in code?

Thanks!

**Comment by GrantJEmerson** [comment]
Unfortunately, that is not the case. Here is the additional information:

- PulleyViewController is not the rootViewController of the window.
- I am creating the PulleyViewController in code along with the content and drawer view controllers in its initializer. Next, I present the pulleyViewController in the code.
- My Drawer View controller was created in a .xib file.

Thanks for the help!

**Comment by brendan09** [comment]
PulleyViewController is designed to be the rootViewController of the window. Although it does work when presented modally, it's not a well tested / supported use case.

The core issue is that the frame is zero before PulleyViewController is added to the window and a layout pass is run. You may be able to get around this by assigning a frame (such as the current view controller's bounds) to PulleyViewController's 'view' property before presenting it. However, I'm not 100% sure that will work since this isn't a case I test.

You can also avoid the error by setting the constraint that this is breaking in your layout to a priority of 750. It will remove the console warning and it shouldn't impact your layout, as long as the rest of your layout is valid.
