### ISSUE TITLE
Can't scroll to bottom of tableView in ".partiallyRevealed" position

### ISSUE THREAD

**Issue by joeuelk** [52inc/Pulley#145]
The tableView in the Pulley Demo contains several rows. When the drawer is in the ".open" position I can scroll to the bottom of the table without issue.
 
But when I only set the supported drawer position to ".partiallyRevealed" I can no longer scroll to the bottom of the table. What's the best way around this?

In my project I may have table rows that are taller than the height of the drawer (depending on screen size).

Thanks!

**Comment by brendan09** [comment]
The Pulley demo artificially stops scrolling when not in the 'open' position in order to more closely replicate the behavior of many screens in the Maps app.

You can disable or modify this behavior by adjusting this line in the Pulley Demo: https://github.com/52inc/Pulley/blob/master/Pulley/DrawerContentViewController.swift#L83

**Comment by joeuelk** [comment]
Worked! Thanks a lot
