### ISSUE TITLE
How to pass data to PrimaryContentViewController?

### ISSUE THREAD

**Issue by joeuelk** [52inc/Pulley#147]
I added a navigationController and need to send the height of it to PrimaryContentViewController.

I'm relatively new to swift and am trying to come up to speed on delegates/protocols which I suspect is  required to make this work.

Near the top of PulleyViewController I added:
```
public protocol NavBar {
    func navBar(navBarHeight: CGFloat) -> CGFloat
}
```
Near the top of PulleyViewController class I added `var navBar: NavBar`.

And in viewDidLoad I added:
```
let navigationBarHeight = self.navigationController!.navigationBar.frame.height
navBar.navBar(navBarHeight: navigationBarHeight)
```

But I'm getting `Property 'self.navBar' not initialized at super.init call` as an error.

Can anyone point me in the right direction. Thanks!

**Comment by brendan09** [comment]
You shouldn't alter or subclass Pulley. It also shouldn't be necessary here.

Can you describe what you're trying to do? I may be able to give you a better approach.

**Comment by joeuelk** [comment]
I'm simply trying to make the height of the navigationController (which I added in the storyboard) available to the PrimaryContentViewController.

**Comment by brendan09** [comment]
Assuming that your navigation controller _contains_ PulleyViewController, you can access this by using the standard `self.navigationController?.navigationBar.bounds.height` at anytime *during or after viewDidAppear* in the view controller lifecycle.

**Comment by joeuelk** [comment]
It works! I was trying to do this in viewDidLoad before in PrimaryContentViewController and it wouldn't work so I assumed I had to grab the value inside PulleyViewController (where it did work inside viewDidLoad) and then pass it over somehow.

Thanks very much!

**Comment by brendan09** [comment]
Since you'll probably encounter things like this in other places: Your PrimaryContentViewController and DrawerContentViewController are loaded _before_ they're added to PulleyViewController's view or viewController hierarchy. As a result, calls that rely on that won't work here. 

-viewDidAppear is the first guaranteed spot where APIs that rely on the view / viewController hierarchy will be functional. This would also be the first point at which you could use self.parent to get a reference to PulleyViewController.

Let me know if you have any other questions!
