### ISSUE TITLE
Can't add a PanGesture to mapView

### ISSUE THREAD

**Issue by joeuelk** [52inc/Pulley#148]
I'm trying to add a pan gesture to the mapView. I added `var panGesture: UIPanGestureRecognizer?` to PrimaryContentViewController.

The action looks like this:
```
    @objc func panGestureHandler(gestureRecognizer: UIPanGestureRecognizer)
    {
        print("panGestureAction")
    }
```

And I'm calling it in viewDidAppear like this:
```
panGesture = UIPanGestureRecognizer(target: self, action: #selector(panGestureHandler(gestureRecognizer:)))
mapView.addGestureRecognizer(panGesture!)
```

I've tried another iteration of this that I know works in another app but can't get it to work in Pulley.

What am I doing wrong?

Thanks!

**Comment by brendan09** [comment]
This isn't really related to Pulley itself. This is more of a side-effect of putting a pan gesture recognizer on a mapview, because it has to deal with the map view's gesture recognizers (which get priority). You can override some delegate methods (and assign the delegate for the gesture recognizers) to allow simultaneous recognition.

However: If you're trying to detect the map panning / moving you should use the appropriate delegate method provided by MKMapView, not a gesture recognizer.

**Comment by joeuelk** [comment]
Thanks, I'll post an update here when I get it to work.

**Comment by joeuelk** [comment]
On another app the following works fine when detecting pan gestures on the mapView:
```
let panGesture = UIPanGestureRecognizer(target: self, action: #selector(handlePan))
panGesture.delegate = self
mapView.addGestureRecognizer(panGesture)
```

But on this project it's choking on `panGesture.delegate = self`.

**Comment by brendan09** [comment]
How is `panGesture.delegate = self.` causing issues? If it doesn't compile, make sure you've marked the class as implementing UIGestureRecognizerDelegate and have implemented any required methods.

**Comment by joeuelk** [comment]
Just saw your response, updated what I did above. Thanks again for your help!
