### ISSUE TITLE
Pass data from drawer to primary view

### ISSUE THREAD

**Issue by clementbalestrat** [52inc/Pulley#158]
I'm struggling to find what's the best way to pass data between the two controllers.
Let's say I select something on the drawer's table and I want to update the primary view's map regarding my selection (like changing the center to a new location).

How would I do that in a non hacky way? I feel like the map controller needs to continuously observe a specific variable in the drawer controller in order to update every time there is a change.

**Comment by brendan09** [comment]
My recommendation is to keep a `weak` property in each controller referencing the other controller so you can pass data between the two (using a protocol rather than referencing the class type is even better).

If you create your view controllers + PulleyViewController programmatically, I recommend setting these variables before you initialize PulleyViewController with the controllers. But, you don’t have to.

If you want to do it later (or if you’re using Interface Builder), at any point after viewWillAppear: in the view controller lifecycle you can get a reference to each view controller by doing the following:

```swift
let primaryContentVC = (self.parent as? PulleyViewController)?.primaryContentViewController

let drawerContentVC = (self.parent as? PulleyViewController)?.drawerContentViewController
```

You’ll need to also cast it to the view controller class (or protocol) as needed. You can then assign it to the weak var property on your class so you always have a way to reference the other VC.

**Comment by clementbalestrat** [comment]
Works great! Thanks.
