### ISSUE TITLE
Bug with Shadow/Dimming View when not using `PulleyPosition.all`

### ISSUE THREAD

**Issue by kcharwood** [52inc/Pulley#159]
First off, thanks for the great library.

I've run into a bug where the shadow/dimming view is off if you aren't returning `PulleyPosition.all` for `supportedDrawerPositions()`.

This can easily be reproduced in the sample project by just making this change in the `DrawerContentViewController`

```Swift
 func supportedDrawerPositions() -> [PulleyPosition] {
        //return PulleyPosition.all // You can specify the drawer positions you support. This is the same as: [.open, .partiallyRevealed, .collapsed, .closed]
        return [.open, .partiallyRevealed, .closed]
    }
```

I need this specifically because the collapsed context doesn't make sense in my app.

I haven't had the chance to dig in and try to figure out the bug yet, but wanted to get a issue filed in case someone can fix it quickly.

Screenshot of the sample app included:

![simulator screen shot - iphone x - 2018-02-01 at 15 58 48](https://user-images.githubusercontent.com/198768/35705717-e0eefe82-0768-11e8-8730-d45ce29d981c.png)

**Comment by brendan09** [comment]
I recently fixed a bug with this in the latest version. Can you ensure you're using the latest version of Pulley (2.2.3)?

If you are, let me know and I'll take a closer look. However, the _current_ Swift 4 / iOS 11 version should have this issue fixed.

Thanks!

**Comment by kcharwood** [comment]
Hi @brendan09!

Confirmed I'm using `Pulley (2.2.3)`.

I pulled the repo down just before filing this ticket, and editing the sample project as described and see the error. Are you able to reproduce it with those simple instructions?

**Comment by brendan09** [comment]
Let me see what I can figure out, and I'll report back. I should be able to fix it quickly.

**Comment by brendan09** [comment]
Ok, it looks like it's triggered by the omission of the `.collapsed` position (you can omit any other one and it still works). Let me figure out why and I'll push an update.

Thanks!

**Comment by kcharwood** [comment]
Great, thanks!

**Comment by kcharwood** [comment]
Hey @brendan09,

One other issue here. May be related, may be a red herring and a complete separate issue. With the same configuration (`[.open, .partiallyRevealed, .closed]`), if the drawer is in the `open` state and I barely drag it down, it snaps to the `.closed` state with no animation. If I use `all`, it seems to behave correctly in and jump to the `.pariallyRevealed` state. Perhaps there is some overall bad state management going on when `.collapsed` is removed from available states?

**Comment by brendan09** [comment]
Yeah, I've found the same problem.

Yes, there is apparently a lot of places that relied on collapsed always being there (before the option to set the available drawer positions was added). I'm currently working through where and why it has this odd dependency on 'collapsed' being present.

**Comment by kcharwood** [comment]
Awesome @brendan09. Let me know if there are any more data points you can provide. Thanks for being so responsive!

**Comment by brendan09** [comment]
@kcharwood Found and fixed both issues (oddly enough, completely unrelated...although both triggered by the omission of `.collapsed`). If you would, please give the current sample project on master a try and see if it works as expected.

If it does, I'll push it over CocoaPods.

Thanks for reporting!

**Comment by kcharwood** [comment]
@brendan09 Awesome. Just tested master and it looks great.

Let me know when you have updated Cocoapods

🍻

**Comment by brendan09** [comment]
Ok, this version is now up on CocoaPods.

You may need to run `pod repo update` before running `pod update` so your local spec repo can find it. The version is 2.2.4.

**Comment by skgwazap** [comment]
I have the same bug.
Version 2.3.0
Swift 4.1 Xcode 9.3b4
Carthage
I'll try stable Xcode 9.3 a bit later.

**Comment by OlivierLapraye** [comment]
I confirm I have the same issue on Xcode 9.3

**Comment by brendan09** [comment]
@skgwazap and @OlivierLapraye please confirm you’re on the latest version of Pulley. If so, please provide a link to a sample project exhibiting the issue. We’ve had multiple confirmed “resolved” reports, so before reopening I’d like to verify it’s an issue with the current version.

Thanks!

**Comment by OlivierLapraye** [comment]
I updated to the 2.3.1 version, the problem is still here for me. Supported positions: `.open`, `.collapsed`. When supported positions include `.partiallyRevealed`, there is no problem. Same behavior on both Simulator and Device
```
let mainVC = MainViewController()
let drawerVC = DrawerViewController.create() // instanciate from Storyboard
let vc = MyRootViewController(contentViewController: mainVC, drawerViewController: drawerVC)

...

navigationController?.pushViewController(vc, animated: true)
```

**Comment by skgwazap** [comment]
I use these two positions `.open, .collapsed`
Unfourchantely, I have no time to play with sample projects currently. So I "fixed" the problem `drawer.backgroundDimmingColor = .clear`:-D

**Comment by brendan09** [comment]
@skgwazap and @OlivierLapraye Here is a gif of the current version of Pulley running on iOS 11.3 (iPhone 7) from Xcode 9.3, using only [.open, .collapsed] as the supportedDrawerPositions.

I'm not seeing any visual issues like the one this issue is discussing (shadow view cropping is in the wrong place). In order to troubleshoot, I need to be able to replicate the issue. Screenshots of what you're seeing are appreciated, as is downloading the Pulley sample project from the repo and verifying the issue exists there with a stock version of Pulley.

I noticed that you've subclassed Pulley as 'MyRootViewController'. Note that I don't offer support for subclassed or altered versions of Pulley, as it's common to break Pulley by doing that. For example, if you override scrollViewDidScroll in your subclass (or any other Pulley method) and don't call the super implementation.

![pulleyexample](https://user-images.githubusercontent.com/1717860/38378750-a99bb98a-38cc-11e8-9b65-dc3fbe22f8db.gif)

**Comment by skgwazap** [comment]
Version 2.3.2
Swift 4.1 Xcode 9.3b4
Carthage
The bug is not fixed.
`extension DrawerViewController: PulleyDrawerViewControllerDelegate {
    
    func collapsedDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat {
        return 184 + bottomSafeArea
    }
    
    func partialRevealDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat {
        return 0
    }
    
    func supportedDrawerPositions() -> [PulleyPosition] {
        return [.open, .collapsed]
    }
}`
this fixes the problem
`    func partialRevealDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat {
        return 184 + bottomSafeArea // return the same value as for _collapsedDrawerHeight_
}`

**Comment by brendan09** [comment]
Ah, I see. Returning zero for partial height is the issue. The value there (even if not used for a drawer stop) is used for calculating when to begin dimming the background, so a value greater than or equal to the collapsed height must be provided or you’ll create an odd scenario.

I’ll consider modifying it to use the collapsed height for the dim calculations when partiallyRevealed isn’t used, however this does take away a customization point for people only using collapsed / open who don’t want the dimming to begin immediately after moving past the collapsed position. 

I’ll take a look later today, however you’re seeing an issue due to returning an improper value for the partial reveal height.

**Comment by brendan09** [comment]
@skgwazap and @OlivierLapraye sorry for the late update on this. Pulley 2.4.0 was just released to CocoaPods and should address this issue. In addition, you can now remove the delegate method implementation for any drawer height you're not using (collapsed / partiallyRevealed). These methods are now marked 'optional' and do not require an implementation. This release also adds a few niceties and fixes a few UI bugs.

You can get the new version of Pulley by running `pod repo update` and `pod update Pulley` (assuming you haven't version locked Pulley).

Please let me know if you encounter any issues. It was tested, but a good amount of position code was refactored...so verification is always appreciated. Thanks!
