### ISSUE TITLE
drawerPositionDidChange delegate method called multiple times in a row

### ISSUE THREAD

**Issue by kcharwood** [52inc/Pulley#161]
I'm looking to use a UIImpactGenerator in my app when the drawer hits different states, and this method seems like a good place to listen for that event. However, I'm seeing the delegate get called multiple times in a row for each event, rather than once (as I would expect).

Is this by design, or this a bug? I can work around this on my side by tracking last known state, and just ignoring states that match the last reported state, but it's not as clean as if the library just sent the callback once for each event.

Thanks!

**Comment by brendan09** [comment]
You should expect this method to be called frequently with duplicate values.

It's called in many scenarios where the drawer layout, position, or settings _may_ have changed, or the size for PulleyViewController itself has been changed.

In addition to drawer changes, you'll also see it called during these events (and potentially more):

* Supported drawer positions has changed.
* viewDidLayoutSubviews was called by the system on PulleyViewController (resulting in a potential new layout / geometry for Pulley, where a drawer or primary content VC should update it's UI).
* The user drags and releases back to the position the drawer was in.

None of these guarantee that the drawer position is _different_ than the last time the delegate method was called. Instead, it indicates that your delegate method should make any UI adjustments necessary for the current state of the drawer as it may have changed. (Heights, sizes, layouts, positions, etc.). Think of it as 'sync UI to the current drawer state' callback rather than one for just literal position changes.

**Comment by brendan09** [comment]
Follow-up: I'd never considered adding Taptic Feedback support to Pulley. If this is something of interest, I'd be happy to add it to Pulley in an update later this evening and you can just enable it / configure it.

Let me know that would appeal to your use case.

Thanks!

**Comment by kcharwood** [comment]
Thanks for the detailed write up. That behavior definitely explains what I’m seeing.

In terms of behavior, I’d like to see a little thud every time the drawer animation completes for the various positions (and only when it animates to that spot, not in a non animation use case).

UIImpactFeedbackGenerator is probably the haptic class I would use... just need to decide what style to support based on feel. Maybe could be an optional property and I could set it externally based on what I want? When it’s set, you call ‘prepare’ then call ‘impactOccured’ internally every time the animation is complete? If the property isn’t set, it’s a no op.

‘’’
public var feedbackGenerator: UIImpactFeedbackGenerator? {
  didSet {
      feedbackGenerator?.prepare()
      }
   }
‘’’


Typed all this on my phone so forgive my typos.

**Comment by brendan09** [comment]
@kcharwood Support for UIFeedbackGenerator subclasses is now available in Pulley 2.2.5 on CocoaPods. You can see the setup for it in the sample project here: https://github.com/52inc/Pulley/blob/master/Pulley/DrawerContentViewController.swift#L46

Let me know if you have any questions!

**Comment by skeeJay** [comment]
This seems to add the haptic feedback in the animation block instead of the completion block (when the user lifts their finger instead of when the drawer "snaps" into its new position). I know you can add a callback to the completion block if the position is changing with setDrawerPosition, but is there a way to achieve the latter effect on manual drawer position change?
