### ISSUE TITLE
PageViewController does not scroll when inside the drawerContentViewController

### ISSUE THREAD

**Issue by cyborgthefirst** [52inc/Pulley#163]
Hey, 

I know its a very weird use-case, but as it happens, the menu inside the app I'm developing consists of a PulleyController and a uias/Pageboy. 

Scrolling left to right inside the PageViewController worked fine in 1.5.4 and also continues to work fine when the drawerState is collapsed. 

Can someone help me with this?

**Comment by brendan09** [comment]
There have been several substantial changes since 1.5.4. Have you completed the migration steps outlined in the README? If not, scroll down to 'iOS 11, Safe Areas, and the iPhone X' in the README. It will require updating your delegate method implementations to use new method signatures.

If you've already done the above and that didn't fix it, then please recreate the issue using the current sample project in the Pulley repo and link a zip file of it. I'm more than happy to take a look.

**Comment by cyborgthefirst** [comment]
Alright, I spoke too soon and I feel sorry for that. It works fine when implementing a minimal case. I will try to compare the example with my production implementation to find the difference. Thank you so much for your help so far.
