### ISSUE TITLE
Disable switching to .open when pulled down 

### ISSUE THREAD

**Issue by woodencoder** [52inc/Pulley#174]
Hi, i was wondering if there's a way to disable transition from `.collapsed` to `.open` when user pulls the drawer down, so that the only way to enter `.open` is by pulling the drawer up.

Thank you

**Comment by brendan09** [comment]
Can you confirm that you’re using the latest version of Pulley? Swiping down shouldn’t cause it to go to open, unless you still are letting go of the drawer _above_ the collapsed position. I believe there were some bug fixes around that a few versions ago.

If you are, can you describe more of what’s happening? The drawer should only go to the next position if you’ve stopped dragging it at least 20 or so points above / below it’s old position (regardless of movement direction when you let go).

You can also try changing the snapMode to .nearestPosition to see if you like the behavior better.

**Comment by woodencoder** [comment]
I have `.collapsed` and `.open` states available for my drawer, so when I pull it down more than 20 points, it than switches to the next available state `.open` (because it has a bigger `rawValue`). So my question is: Is it possible to make it so we can go to the "upper" states only if we pull up, and we can go to the "lower" states only if we pull down?

**Comment by brendan09** [comment]
Changing the snapMode to .nearestPosition (instead of its default, which uses the 20 pt threshold) will help a lot. It’ll expand the 20pt region to “halfway” between collapsed and open. As long as they let go of the drawer less than halfway to open, then it’ll go back to collapsed.

However, there isn’t a way handle this based on “last swipe direction”. It projects the final destination based on scrolling direction and speed, and then picks an appropriate position based on the snapMode setting.

**Comment by woodencoder** [comment]
Got it! Thanks
