### ISSUE TITLE
Question on temperature tracking label

### ISSUE THREAD

**Issue by daver234** [52inc/Pulley#178]
Hi,

I have a containerView that moves with the drawer.  I did the bottom constraint to the bottom of the superview of the primaryVC.  Works fine on a iPhone X but goes below the drawer in the iPhone 6s. Once I open and close the drawer, it adjusts fine and tracks the drawer.  Any suggestions for what to change to get the initial tracking to work?  I did implement your drawerChangedDistanceFromBottom method just like in your Pulley demo.  

Are there any aspects of the drawerVC constraints that affect the temperature tracking type button?

Side note:  In addition to the container view, I have a button that also tracks the bottom drawer.  Same issue. Thanks.

**Comment by brendan09** [comment]
Make sure your constraint is to the superview itself, and not the safe area or superview margin.

If you’re designing in InterfaceBuider, the starting values for the layout will be wrong on either iPhone X or regular devices, depending on what the IB setup was when you made the constraints.

The delegate methods aren’t called until the drawer moves, which is why you’re seeing that behavior. In viewWillAppear (or viewDidAppear) you can call setDrawerPosition() to cause the delegate methods to be delivered updates. That should sync your UI.

Drawer VC constraints won’t impact the temperature button.

**Comment by daver234** [comment]
Brendan,

Thanks for the quick response.  I have the bottom constraint set to the superview itself, but I'm still having the problem.

I tried the bounce method but that didn't work.

What did work is  to call setDrawerPostion in viewDidAppear to .closed and then right after to .collapsed.  That did sync the UI and it doesn't appear to be noticeable to the user.  Sill would be nice to know why this is occurring just so I know what I'm doing wrong.  But this work around does the job now.  Thanks.

**Comment by zntfdr** [comment]
Thanks @daver234 for the solution!
