### ISSUE TITLE
How to disable landscape (.automatic) mode?

### ISSUE THREAD

**Issue by joeuelk** [52inc/Pulley#179]
In PulleyViewController .bottomDrawer is set:

```
public var displayMode: PulleyDisplayMode = .bottomDrawer {
        didSet {
            if self.isViewLoaded
            {
                self.view.setNeedsLayout()
            }
        }
    }
```

In PrimaryContentViewController I have the following in viewWillAppear:
```
if let drawer = self.parent as? PulleyViewController
        {
            drawer.displayMode = .bottomDrawer
```

Nowhere can I find `.automatic` specified in the code yet when I tilt the phone sideways the UI still updates for landscape mode. Any ideas?

My immediate goal is to have Pulley stay in portrait mode but have modals I will add later (for displaying websites, etc.) operate in landscape and portrait mode.

Thanks!

**Comment by brendan09** [comment]
Setting it to .bottomDrawer in viewWilAppear in the sample project works as expected. The phone will still go to landscape, but it won't convert to the "side panel" display mode.

'bottomDrawer' does _not_ prevent the orientation change, it just keeps the drawer at the 'bottom' of the screen instead of converting into the side panel mode.

**Comment by joeuelk** [comment]
OK... that makes sense. Thanks
