### ISSUE TITLE
Allow overscroll above maximum height?

### ISSUE THREAD

**Issue by azhang66** [52inc/Pulley#180]
In the iOS Maps app, [for example](https://streamable.com/4nugx), the drawer is able to be temporarily dragged above the maximum position. When the drawer is released, however, it bounces back to the maximum height.

Would this behavior be possible in Pulley?

**Comment by brendan09** [comment]
This isn’t something I’m going to prioritize adding to Pulley, but I’m happy to review a PR for it if it doesn’t have other side effects.

**Comment by brendan09** [comment]
@azhang66 This turned out to be easy to implement while I was in here working on the other issue.

This is now on master and on CocoaPods as Pulley 2.3.0. You may need to run `pod repo update` before `pod update Pulley` to get it.

It will allow up to 15 points of over-scroll. I was looking at allowing more, but it results in some UI artifacts that would require breaking backwards compatibility to fix. I don't want to cross that bridge for this, but 15 points of over scroll definitely gets the effect across.

Try it out and let me know what you think. Thanks!

**Comment by azhang66** [comment]
Works perfectly. Thanks!

**Comment by sadanro100** [comment]
How can I disable this behaviour? It seems like can't disable it the way it's implemented

**Comment by brendan09** [comment]
You are correct that it isn’t publicly able to be disabled right now. 

If you’re interested in it being able to be disabled, please make a new issue and I’ll try to get to it this weekend.

I’d almost be interested to know (in that issue) why you’d like the behavior disabled, as it is something Apple Maps does and does make the drawer feel more natural.

Thanks!

**Comment by sadanro100** [comment]
It was breaking some constraints in the primaryViewController but ive just realised it was my mistake.

Sorry about that. It's fixed now and you're right, there's no reason the remove the bounce.

Thanks again.
