### ISSUE TITLE
Getting current visible drawer height

### ISSUE THREAD

**Issue by jberglinds** [52inc/Pulley#196]
Hi, I'm having problems getting the current visible drawer height. 
What I want to do is to have a tab bar controller within the drawer and having the tab bar stick to the bottom at all times.

I have a custom tab bar controller which updates the placement of the tab bar in `drawerChangedDistanceFromBottom(drawer:distance:bottomSafeArea)` and that works fine. However, when the view loads that method is not called, so I need the `distance` value in `viewDidAppear` in order to position it. I would also like this value in `viewWillLayoutSubviews()` in order to make it place itself correctly on interface rotations.

I feel like I must be missing something because I can't figure out how to trigger the delegate method or getting the value directly. I've looked at the `visibleDrawerHeight` property of the PulleyVC but it just gives the same constant value at all times. I expected it to return the same value as the `distance` parameter in the delegate method.

Any pointers would be helpful. The documentation has been great apart from me not figuring out this. Thanks for making Pulley. 🙂

**Comment by jberglinds** [comment]
Great, thank you for the quick answer. I'll try your workaround!

**Comment by jberglinds** [comment]
It worked very well. Thank you. 

I do have another problem now though that's not really directly related to this one. I hope it's fine that I use this issue. The safe area seems to behave differently based on the current state of the drawer.  See attached gif for how the tab items place themselves when rotating the device with the drawer in the .open state as opposed to a collapsed one. _Maybe you know why this happens?_
![2018-05-06 18_20_33](https://user-images.githubusercontent.com/6368728/39675350-34ad989a-515a-11e8-8b38-0e7f147bdb1d.gif)

**Comment by brendan09** [comment]
Unfortunately, that’s a side effect of changing the height of a UITabBar. It’s always meant to be a fixed size, and not to have a height that can change. (Or use a non-default height that UIKit manages). 

You could try calling -layoutIfNeeded on it during the size transition method you can override in UIViewController.

I haven’t looked at the current UITabBarController implementation after the iOS 11 Safe Areas addition, but it wouldn’t surprise me if it behaved like UINavigationController in how it renders navigation bars that extend under the status bar.

UINavigationController doesn’t actually change the height of the navigation bar. It’s always 44 pts (assuming not in minimal landscape mode). When the bottom Y point of the navigation bar is exactly Safe Are + 44.0, it artificially extends it’s background under the safe area. This is an internal, somewhat undocumented, behavior. If you were to have the navigation bar 1pt in either direction then it doesn’t do it and you just see a 44pt  navigation bar. 

I say all of that to say: Try making the frame always be 49.0 pts tall, and position it so that it’s bottom is right above the bottom safe area. This may not work, but it’s a guess based on how navigation controllers / navigation bars work. 

If that doesn’t work, try putting it at the same position mentioned in the previous paragraph and adding a visual effect view (or solid color view, if you want a solid color tab bar) to span the distance from the bottom of a 49.0 height tab bar to the bottom of the screen (height of the safe area).

**Comment by jberglinds** [comment]
The only thing I could make work was your last solution. Now everything works great. 
Thank you for all the help! 🙏

**Comment by brendan09** [comment]
Glad you found something that works! Let me know if you have any more questions.

I'll post back here once I've added something to prevent the original workaround. Thanks!

**Comment by brendan09** [comment]
@ jberglinds Hello! Sorry for the extended delay on this. An update to Pulley is now available on CocoaPods and master supporting this. Pulley version 2.4.1. You may need to run `pod repo update` and then `pod update Pulley` to see the update, as long as you haven't locked your Pulley version.

A new property is available on PulleyViewController named `drawerDistanceFromBottom` that will provide the current distance and bottomInset values. You may also find the new property `pulleySafeAreaInsets` helpful, as it provides an easy way to get Pulley's Safe Area on iOS < 11.0 

Let me know if you have any questions! Thanks
