### ISSUE TITLE
need help on pathing variables

### ISSUE THREAD

**Issue by almazini** [52inc/Pulley#2]
I am trying to path a variable from my view controller to pulley. 
I managed to pass it to PulleyViewController using prepareForSegue method.
but I cant understand how to pass it to PrimaryViewController and DrawerViewController. 
Can you please help me? Thanks

**Comment by brendan09** [comment]
Sure, can you explain what you're trying to do in detail?

**Comment by almazini** [comment]
i have a viewcontroller where user is selecting one of the options. 
Previously I had secondViewcontroller where 50% of screen was map and 50% of screen was table. I was using prepareForSegue method to pass the selected option to secondViewController(map annotations and table were populated according to selection)
Now I want to use Pulley and trying to find out how to transfer selected option to PrimaryViewController and DrawerViewController

**Comment by brendan09** [comment]
You shouldn't transfer values directly to the PulleyViewController. I'm guessing you modified it to accept bName? Don't do that.

What you want to do is access the primaryContentViewController and drawerContentViewController properties of the PulleyViewController and set the values directly on your own View Controllers. Don't set / modify PulleyViewController directly.

**Comment by almazini** [comment]
> What you want to do is access the primaryContentViewController and drawerContentViewController properties of the PulleyViewController and set the values directly on your own View Controllers. Don't set / modify custom properties on the PulleyViewController directly.

But how can I do that? 
I have created a variable in primaryContentViewController but it is not visible in drop down list:
![screen shot 2016-08-15 at 07 42 54](https://cloud.githubusercontent.com/assets/4295443/17655869/0602127a-62bc-11e6-8c24-2fb2f93f6f4a.png)

**Comment by brendan09** [comment]
That's because primaryContentViewController is defined in PulleyDrawerController as a generic UIViewController, kind of like the destinationViewController in your segue. You need to cast it to the appropriate type before you can access the variables in your custom subclass. It's the same concept as how you cast segue.destinationViewController as! PulleyViewController before you can use it.

**Comment by almazini** [comment]
still not working. 
Or maybe I don't understand how should I do it. 
![screen shot 2016-08-15 at 08 13 15](https://cloud.githubusercontent.com/assets/4295443/17656252/717bc6aa-62c0-11e6-8eb3-8448361a5d69.png)
I am quite new in ios development.

**Comment by brendan09** [comment]
Since you're new to iOS: Don't force unwrap regularly. It's a really bad habit. Always properly unwrap or use optional chaining. Like, 75k+ lines of Swift code generally has less than 5 force unwraps if it's well written.

The problem that you're having now is that the Storyboard hasn't loaded your view controllers into the drawer. Your force unwrap ! is causing a crash because primaryContentController is nil. 

Have you properly connected the view controllers to the Pulley Drawer in Interface Builder? I see you have the content containers linked, however do you have your VCs linked to the containers with an embed segue?

**Comment by almazini** [comment]
I have connected the button (on my mainVC) to PulleyDrawerController and have chosen "show" option. And entered identifier for that seague.

![screen shot 2016-08-15 at 07 49 15](https://cloud.githubusercontent.com/assets/4295443/17656751/16e30e28-62c6-11e6-91af-062266b72d78.png)

That is the only connection I have. 

PulleyDrawerController is connected to PrimaryVC and DrawerVC as per your project

**Comment by brendan09** [comment]
Did you connect the 2 container views to the appropriate outlets on the pulley drawer controller? In the debugger screenshot a couple of posts up those are nil, indicating the outlets haven't been connected in Interface Builder.

**Comment by almazini** [comment]
yes they are connected.

![screen shot 2016-08-15 at 09 03 22](https://cloud.githubusercontent.com/assets/4295443/17656947/279c53ee-62c8-11e6-8931-edb1a5093ea8.png)

**Comment by brendan09** [comment]
Before you try to use the primaryContentViewController, call loadViewIfNeeded() on the Pulley Drawer Controller. If that view hasn't loaded yet then the connections won't be made and the view controller variables won't be populated. That's likely what's happening here.

**Comment by almazini** [comment]
It helped and application is not crushing now ... but still not working 

now my prepareForSegue method looks like this:
```

    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        
        if segue.identifier == "showLocation" {
            
            let viewController = segue.destinationViewController as! PulleyViewController
            
            viewController.loadViewIfNeeded()
            
            let targetVC = viewController.primaryContentViewController as! PrimaryContentViewController
            
            targetVC.newName = "test"
            
        }
    }
```

In every class's viewDidLoad method I created a print function with name of class. 

In PrimaryContenctViewController class I also aded a print of my variable to check if it is been transfered there. 

This is what I get: 
![screen shot 2016-08-15 at 10 07 12](https://cloud.githubusercontent.com/assets/4295443/17657944/1cbdb7a8-62d0-11e6-9e6a-8f48f2924bb7.png)

1)so the first VC which was loaded was PrimaryContentVieController .... 
2)the variable is empty .. it was not transfered
3) DrawerContentVC was loaded
4) and the last one goes PulleyViewController. Isn't it strange? I thought it will be the first one to load?

**Comment by brendan09** [comment]
Because your other 2 VCs are dependencies of  the Pulley Drawer, their views will have to load first before the Pulley Drawer is fully loaded. That's why you're seeing this.

Calling loadViewIfNeeded() forces the hierarchy to load.

Once loaded and connected to the variables, you can set the values.

You're likely not correctly handling your properties in your VCs. I'm gonna go out on a limb and say you were reading their values to configure your UI in viewDidLoad? If so, that won't work because we forced the view hierarchy to load _before_ you set the variables. You should override didSet for your variables and update the UI, if the UI has been loaded.

**Comment by almazini** [comment]
Oh Brendan, you are speaking Chinese to me :) I don't have enough experience to understand what do you mean by saying "You should override didSet for your variables and update the UI, if the UI has been loaded."

I have uploaded added an initial VC with table to your project. Could you have a look?
[Pulley-master copy.zip](https://github.com/52inc/Pulley/files/419583/Pulley-master.copy.zip)

**Comment by brendan09** [comment]
You're not setting newName until _after_ viewDidLoad is run...so you're not going to see it in the print out.

If you modify your newName to include a didSet handler, then you'll see that the value is set...you just need to update your UI / use it. You won't be able to do it in -viewDidLoad.

`    var newName : String = "" {
        didSet {
            print("The value was updated to: \(newName)")
            
            // Update your UI (if it's loaded) here.
        }
    }
`

**Comment by almazini** [comment]
thank you
