### ISSUE TITLE
Top space bug in interface builder

### ISSUE THREAD

**Issue by Alex293** [52inc/Pulley#20]
Hi,

If you instantiate a pulley controller in interface builder there is an additional 8 height space between the vc top and the content drawer top. You can detect it by setting up a vc in storyboard and the replacing it by the same vc in code. The vc will then go down by 8.

If someone need a fix asap :
A workaround is to set again the content vc in viewWillAppear by code

**Comment by brendan09** [comment]
Can you upload a zip file showing the issue? It may have something to do with some IB constraints.

**Comment by Alex293** [comment]
I don't have time right now but you can see it with the demo, in the content vc you have a 8 height constraint to the top and when you run you have more (16). Tho if you load the same vc by code you don't have this spacing

**Comment by Alex293** [comment]
Another way to spot it is that you've set the height of the collapsed part to 68, added a view of 68 but the view isn't completely shown (you need to scroll a bit to seen the table top separator). Anyway i've looked a the code and the interface builder of the demo and this space is set nowhere. I suspect that this is kind of included with the embed segue. This need further investigation but for now I'm gonna stick with my solution to set my content drawer in view did appear

**Comment by brendan09** [comment]
Thanks for the details! I'll take a look this week and see what I can find.

**Comment by brendan09** [comment]
The problem is that by default Interface Builder connects it to the "Top margin" of the view it's contained in. Container Views apparently have a default top margin of 10pt.

If you select the constraint and open the side menu to adjust it then you can tell it to constrain it to the "Superview.Top" property of the view, rather than the "Superview.Top Margin"

See the screenshot below and un-checkmark the "Relative to Margin". Voîla! Problem fixed.

<img width="267" alt="screen shot 2016-10-25 at 9 20 30 pm" src="https://cloud.githubusercontent.com/assets/1717860/19709993/e2f6b5e0-9af8-11e6-85db-e190a43daf5f.png">

**Comment by Alex293** [comment]
In deed solved, thanks
