### ISSUE TITLE
View hierarchy question

### ISSUE THREAD

**Issue by joeuelk** [52inc/Pulley#203]
Is it possible to display a view that is created in PulleyContentViewController **above** DrawerContentViewController?

When I swipe the drawer to the "open" position I want a UIView on the PulleyCVC to stay on top.

Thanks

**Comment by brendan09** [comment]
No, PulleyViewController manages it's own view hierarchy and won't readily work with additional views placed inside it.

My recommendation is to create another view controller that you can embed PulleyViewController in. You can then put views on top of the container view where PulleyViewController is embedded in this new view controller.

If you want an example, let me know. It's fairly easy to do with container views in Storyboards.

**Comment by joeuelk** [comment]
That's an interesting idea. If it's not much trouble I'd love to see an example of how to do that.

**Comment by brendan09** [comment]
Sure, here's a version of the sample project. Important: This is an old sample I put together with someone that uses a much older version of Pulley, so don't grab the Pulley code out of this....but since this doesn't actually use any Pulley features to accomplish this trick you should be fine.

https://www.dropbox.com/s/hurzxag6tx64zbp/Pulley-Floating%20Content.zip?dl=0

Checkout the Storyboard file + run the app.

**Comment by joeuelk** [comment]
That's great! Thanks so much. I think this will get me what I need. I really appreciate it.
