### ISSUE TITLE
Bug with modals

### ISSUE THREAD

**Issue by Alex293** [52inc/Pulley#21]
Hi this time It's a more important bug :)

After dismissing a modal displayed over the pulley, the content drawer bugs.
I've managed to use only modal segues over full screen so it keeps my drawer so problem solved but when I don't manage my self the segue (Facebook login for ex) the bug stays. Think there is something to do with define context or something like this but I'm not expert with those.

**Comment by brendan09** [comment]
Looks like it needs -definesPresentationContext set to true. I'll try to push that as a default in the next update. In the mean time, you can try setting the Pulley drawer's -definesPresentationContext property to true and see if that helps.

**Comment by Alex293** [comment]
Doesn't seems to do anything I'll try to investigate this more

**Comment by Alex293** [comment]
I've tried lots of things but nothing seems to solve my issue. I didn't managed to reproduce the bug from the example, however I know what is the source of the issue : the passthrough view (in blue) of the pulley is out of the screen after dismissing view : 

<img width="302" alt="screen shot 2017-01-24 at 15 11 04" src="https://cloud.githubusercontent.com/assets/5930273/22250484/5b188c7a-e247-11e6-9b47-1b638e617be8.png">

While this is its position when I first load the view and after a dismiss if my modal is presented over full screen : 

<img width="327" alt="screen shot 2017-01-24 at 15 10 51" src="https://cloud.githubusercontent.com/assets/5930273/22250485/5b46d4ea-e247-11e6-891d-f6929bd9eb8c.png">

The thing I don't understand is that this view is not accessible out of the lib so there is no way I've modified it.

**Comment by brendan09** [comment]
If anyone has a reliable way to replicate this, I'm happy to take a look. It works with modal presentations that I've tried (with definesPresentationContext set to true). A release coming out later today defaults definesPresentationContext to true.

**Comment by fariz-siracli** [comment]
Hello guys. I pass some list to drawer's tableview, but when i open drawer's table i see that row count multiplied by 2 and also all the rows were duplicated. Is it intented to be like this ?

**Comment by brendan09** [comment]
@fariz-siracli Please open another issue if you have an unrelated question. But, at first glance: You should replace the drawer content VC with a custom one you write. The implementation you're referring to wouldn't have anything to do with Pulley VC and would just be a bug in your own code, as Pulley VC doesn't manage any table views for you.

**Comment by pschneider** [comment]
I may have found a way to reproduce this in our project. Investigating.... will try to encapsulate this into a sample project sometime this week.

**Comment by ethansinjin** [comment]
I know this issue hasn't been touched in a while, but I'm still seeing this problem. I can try to upload a video of the issue as well as a sample project describing the issue if that would help

**Comment by brendan09** [comment]
@ethansinjin (some things to test, might help narrow it down) In your drawer content or main content VC, what happens if you do this in viewWIllAppear or viewDidAppear?

     self.parent?.view.setNeedsLayout()

If that fixes the issue (even if it has a UI glitch), I have some ideas on what may be wrong.

If you can put together a sample with the issue (even if derived from the sample project in the repo), I'd much appreciate it. I can find you a solution then. I think another user was going to try to upload a sample project, but one never found its way to the issue.

Happy to take a look.

**Comment by ruilunli** [comment]
@brendan09  Based on the sample project, I added a view controller before the pulley view controller. And in the drawer content view controller, instead of `drawer.setPrimaryContentViewController`, I present as a modal. When the modal dismiss, the drawer view controller bugs.
<img width="281" alt="screen shot 2017-08-03 at 7 50 52 pm" src="https://user-images.githubusercontent.com/25217746/28917675-9921fdd8-7885-11e7-8ea4-c99d96e649d9.png">
<img width="730" alt="screen shot 2017-08-03 at 7 51 06 pm" src="https://user-images.githubusercontent.com/25217746/28917680-9c36c6d4-7885-11e7-8845-31f64d754651.png">
<img width="1048" alt="screen shot 2017-08-03 at 7 52 22 pm" src="https://user-images.githubusercontent.com/25217746/28917685-9eaff386-7885-11e7-9088-71289ae964b2.png">

**Comment by brendan09** [comment]
@ruilunli I've tried doing what you described, but haven't been able to replicate it (even on iOS 9). Can you post a download link to the sample project in a broken state (or email it to me: brendan@52inc.com). Once I can replicate it, I can get a fix out for you. Thanks!

**Comment by brendan09** [comment]
@ruilunli Ok, I've found the issue.

The core of the issue is in these 2 lines in your sample:

          self.definesPresentationContext = true

and

          primaryContent.modalPresentationStyle = .currentContext

When you change the context to be a view controller inside of a nested view controller hierarchy, _and_ do a regular (not 'over') presentation style you're creating an issue in how UIKit handles view controller presentation.

When you don't use an 'over' presentation style, the view of the previous view controller that was defining the presentation context is removed from it's superview (which is typically the window). Since you change that to the drawer view controller, the drawer view controller's view is removed from it's superview. When you dismiss the view controller that you presented, UIKit adds it back...but it adds it back in the wrong place. It puts it directly into the window, rather than back into it's nested view inside of Pulley.

This isn't a bug in Pulley, so much as a way that UIKit doesn't intend defining context for presentations to be used.

You can solve this by using the 'overCurrentContext' presentation style:

          primaryContent.modalPresentationStyle = .overCurrentContext

I've also written a patch for Pulley that will prevent this from being an issue. It's a little hacky, but does resolve the problem. I'll push that to CocoaPods this afternoon.

Thanks so much for your help in tracking this down! (Also: Interesting way to prevent secondary 'drawer' views that I hadn't considered.)

**Comment by ruilunli** [comment]
Thanks for spotting!
