### ISSUE TITLE
passing array data

### ISSUE THREAD

**Issue by JasonGreenAmerica** [52inc/Pulley#22]
what's the best way to pass an array into pulley so that both drawer and primary can see it...

-Thanks

**Comment by brendan09** [comment]
The pulley drawer is not meant to hold data, and shouldn't in a well architected app. It's purely a presentation component. You'll need to share data via another mechanism.

Some things you may consider are:
• A shared data source object.
• Direct references between the controllers.
• A singleton.

You should _not_ attempt to pass data to the drawer controller, store data in the drawer controller, or traverse the view controllers in the drawer controller in an attempt to find another VC. 

Pretend the pulley drawer wasn't in the equation. Keep in mind, this very well may mean that you need to create and setup the controllers in code so that you can assign your data source to both your content and drawer view controllers before you setup the pulley drawer with them.
