### ISSUE TITLE
Unnecessary Animation

### ISSUE THREAD

**Issue by eitanaviv** [52inc/Pulley#228]
Hi there,
I've just implemented your library in my app and i have a TabBarController.
I set initialDrawerPosition to "closed" (from IB) and on load it works fine, the drawer is closed, but when i start switching tabs and return to the tab with Pulley, i always see a closing animation.
If i set other initialDrawerPosition like "partiallyrevealed" and do the same procedure there is no animation at all as it supposed to be.
Am i missing something?
Thanks!

**Comment by brendan09** [comment]
Do you have any code in viewWillAppear or viewDidAppear that changes the drawer position? Or that calls Pulley in some way?

It should work fine in a tab bar controller unless something is causing Pulley to change drawer position on appearance.

**Comment by eitanaviv** [comment]
Hi @brendan09, I have the following code in the ViewController that delegates `PulleyDrawerViewControllerDelegate`:
```swift
class MapBottomSheetViewController: UIViewController, PulleyDrawerViewControllerDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
    func collapsedDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat {
        return 100
    }
    
    func partialRevealDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat {
        return UIScreen.main.bounds.height / 2
    }
    
    func supportedDrawerPositions() -> [PulleyPosition] {
        return [PulleyPosition.closed, PulleyPosition.collapsed, PulleyPosition.partiallyRevealed]
    }
}
```

In the other ViewController that delegates `PulleyPrimaryContentControllerDelegate` i have nothing that regards to the library.

Thanks for the fast reply.

**Comment by brendan09** [comment]
@eitanaviv I'm unable to replicate your issue in the sample project. Are you calling anything related to Pulley in viewWillAppear, viewDidAppear, viewDidLayoutSubviews, or viewWillLayoutSubviews?

If possible, please replicate it in the sample project and provide a download link and I can see what's happening. Thanks!

**Comment by eitanaviv** [comment]
Hi @brendan09, I've used your sample project and everything seems to work fine (i also don't get the closing animation in my project). So I compared my project and storyboard to your sample project and it seems to be the same. What could it possibly be? If it helps, i'll be glad to email you the files of my project the relates to Pulley.
Thanks!

**Comment by brendan09** [comment]
Sure, I’m happy to take a look. Make sure whatever you send me builds (if you don’t send me your complete project). 

Brendan@52inc.com

**Comment by edwardmp** [comment]
I think I'm actually seeing the same behavior. When the drawer is closed, and I (for instance) present a modal view and then close it again, I see a the drawer dismissing quickly as well, while it wasn't even visible before... If I can reduce this to a small example I will share it here.

**Comment by eitanaviv** [comment]
@edwardmp This is exactly what is happening to me.
If you call this function `self.pulleyViewController?.setDrawerPosition(position: .closed, animated: true)` does it really animates the closing animation? Because in my case it doesn't.

**Comment by brendan09** [comment]
As a short term work around, set your modal presentation style as “over current context” or “over full screen”. 

The issue likely comes from re-running the appearance setup code. 

If someone can replicate it in the sample project, I’m happy to get a fix in ASAP. Otherwise I’ll have to wait until I have time to try and replicate it.

**Comment by edwardmp** [comment]
@brendan09 thanks! Already fired off the debugging but it wasn't some very obvious problem. Indeed seems to have to do with some appearance related code. Will investigate further if I have time.

**Comment by eitanaviv** [comment]
@brendan09 I'm unable to replicate this issue in your sample project, but i'll keep try and of course keep you updated.
@edwardmp I'm not showing anything on top. My use case of Pulley in my project is the same like the sample project (except that i have a bug) - no modally or anything else, just the bottom drawer and the main controller.

**Comment by edwardmp** [comment]
@brendan09 do you have any pointers where this issue might arise? Did a few debugging sessions but couldn't find anything yet unfortunately.

**Comment by brendan09** [comment]
Modifying Pulley’s values, delegate values, or position in viewWillAppear, viewDidLayoutSubviews, or viewWillLayoutSubviews can cause glitches like that.

**Comment by eitanaviv** [comment]
@brendan09 I've managed to reproduce the issue when there is no closing animation of the drawer with the following steps:
1. Cloned the example project.
2. Added Google maps instead of MKMapKit.
3. Added the following delegation:
`func mapView(_ mapView: GMSMapView, willMove gesture: Bool) {
        self.pulleyViewController?.setDrawerPosition(position: .closed, animated: true)
    }`
4. When drawer is opened, moving the map will make it close without animation.
That's it. I can send you the project itself if you prefer.

Regarding the weird drawer appearance, I'm still unable to reproduce this issue.
I'll continue to try and keep you updated.

**Comment by brendan09** [comment]
Here are some things that might be happening:

1. Verify that delegate method is called on the main thread. If it isn’t, it could cause issues.
2. Google Maps may be calling that method multiple times quickly in succession. Make sure that isn’t the case.
3. Google maps may be removing other animations from layers.
4. In some circumstances, UIKit will wait to start an animation while another one is ongoing (google maps panning in this case). It resumes at the progress point where the animation would be had it started at the correct time, once the other animations complete. In this case, the drawer would snap to closed once google maps panning animation had completed.

Because this involves a 3rd party library causing the issue, it’s not something I’m going to further troubleshoot. If you can replicate it with MKMapView and UIScrollViewDelegate/MKMapViewDelegate, then I’m happy to take a look. However, if it only happens when Google Maps is involved then it’s likely Google Maps is doing something with animation layers that’s affecting Pulley.
