### ISSUE TITLE
setNeedsSupportedDrawerPositionsUpdate bug

### ISSUE THREAD

**Issue by KarlChow92** [52inc/Pulley#23]
I am currently writing an app where the `drawerViewController` is an `UINavigationController`. Based on in which screen I am in the `UINavigationController` the `drawerHeight` should adjust and the `positions` should only support a certain one.

In my `PulleyViewController` I implemented the delegate: `PulleyViewController` and for each method I return a variable that represents the active 'state'. This state is given by the `NSNoificationCenter` and it looks like this:
```
@objc func setPulleyPossibilities(notification:NSNotification){
        if let positions = notification.object as? [Int] {
            if positions.isEmpty {
                self.drawerPositions = PulleyPosition.all
                return
            }
            var newPositions:[PulleyPosition] = []
            for position in positions{
                newPositions.append(self.determinePositionBy(position: position))
            }
            self.drawerPositions = newPositions
        }
        self.setNeedsSupportedDrawerPositionsUpdate()
    }

``` 
The thing is, that I red in the usage that I need to call `self.setNeedsSupportedDrawerPositionsUpdate()` after doing this but this does not happen unfortunately. I also set the delegate and I see it actually updating in the debugger of xcode. 

Another strange thing is that I've set a breakpoint in the delegate methods but they don't fire for somer eason but, the variables in the `PulleyViewController` is updated!

**Comment by brendan09** [comment]
You should not subclass or alter PulleyViewController. The delegate methods should NOT be implemented in the PulleyViewController. By directly altering values, you're likely bypassing the mechanisms in place to make things work properly.

If you need different positions to be available based on the current VC shown in the navigation controller:

• Subclass UINavigationController and implement the appropriate PulleyViewController delegate methods there.

• In the UINavigationController subclass, also implement the UINavigationControllerDelegate so that you can tell the pulley view controller to refresh the supported positions when needed.

Again, I just want to reiterate: The PulleyViewController class should be used as-is. Don't subclass or alter it. I don't intend on supporting those scenarios, so if you continue down that path I won't be able to provide assistance as I can't guarantee you haven't broken or bypassed something you shouldn't have.

**Comment by brendan09** [comment]
In addition, the positions are queried from the view controller contained in the pulley drawer directly....not from the delegate the pulley drawer offers. The delegate it offers is for observation of events only, and is marked as such (the protocol it accepts does not include the methods for positions).

**Comment by KarlChow92** [comment]
@brendan09  It worked! Thank you. And I am obviously actually a bit wrong in my coding style. Thank you!
