### ISSUE TITLE
Remove pulleyViewController extension

### ISSUE THREAD

**Issue by icecrystal23** [52inc/Pulley#237]
I would like to request that the pulleyViewController extension on UIViewController be removed from the pod.  It makes assumptions about app view hierarchy and prevents me from using reasonable variables names in my application code.  I wanted to create a "pulleyViewController" variable on a single view controller that will contain a pulley, but I had to call it something else because of the extension.

Request to revert 75347b0f401de44ec518e36bb203f10b037bd7cf

**Comment by brendan09** [comment]
It originally wasn't included, however I had numerous people request that it be added. Because this would break people's existing apps (and the implementation should work in _most, if not all_ view controller hierarchies that have parent/child relationships) I don't feel that rolling this back would be in the best interest of the general community.

If the accessor doesn't work for you, I recommend using a different variable name (such as 'pulleyController'), or opening a PR that fixes that view controller hierarchy assumptions that cause the extension not to work for your app.

**Comment by icecrystal23** [comment]
I'm disappointed that numerous people requested this, as I feel it promotes bad UI programming practices.  However, given that it's what your consumers want, then I will close this.

**Comment by brendan09** [comment]
I think the thought process was that it makes utilizing Pulley more akin to accessing the nearest UINavigationController, UITabbarController, or UISplitViewController via those properties on UIViewController. I didn't write the implementation for the extension, however it seems to work in roughly the same circumstances as those examples provided by UIKit and generally doesn't harm anything.

It's likely possible to write a sub-podspec that _doesn't_ include it, and that may be worth doing for people who determine they don't like that functionality. I'll take a look at the feasibility of that in the near future, or accept PRs that enable that.

Thanks
