### ISSUE TITLE
Help please - facing issues with tableView.realoadData()

### ISSUE THREAD

**Issue by pawangiri** [52inc/Pulley#238]
All I am trying to achieve is reload data when new data is available in the tableView. But I get tableView as nil when I try reloading data.

This is main code responsible for the act

```
class DrawerContentViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
    
    
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var headerSectionHeightConstraint: NSLayoutConstraint!
    
    public var listOfPosts = [Post]() {
        didSet {
            refreshTableView()
        }
    }
    
    
    fileprivate var drawerBottomSafeArea: CGFloat = 0.0 {
        didSet {
            self.loadViewIfNeeded()
            
            // We'll configure our UI to respect the safe area. In our small demo app, we just want to adjust the contentInset for the tableview.
            tableView.contentInset = UIEdgeInsets(top: 0.0, left: 0.0, bottom: drawerBottomSafeArea, right: 0.0)
        }
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        self.tableView.dataSource = self
        self.tableView.delegate = self
        self.tableView.register(UINib.init(nibName: "TableViewCell", bundle: nil), forCellReuseIdentifier: "listViewCell")
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 50
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "listViewCell", for: indexPath)
        return cell
    }
    
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 215.0
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        
        let primaryContent = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "PrimaryTransitionTargetViewController")
        
        pulleyViewController?.setDrawerPosition(position: .collapsed, animated: true)
        
        pulleyViewController?.setPrimaryContentViewController(controller: primaryContent, animated: false)
    }
    
    func refreshTableView() {
        DispatchQueue.main.async {
            self.tableView.beginUpdates()
            self.tableView.reloadData()
            self.tableView.endUpdates()
        }
    }

}
```

When `did set` gets triggered later in app, tableView is nil

**Comment by brendan09** [comment]
There are only a few things that can cause this:

• Your IBOutlet isn’t connected in Interface Builder. Verify it’s connected.
• The view for your view controller hasn’t been loaded yet. Put a call to “self.loadViewIfNeeded()” Immediately before attempting to refresh the table view (or the first line in the refresh function).
• If you remove the view controller’s view or table view from the windows view hierarchy, it will be deallocated because the variable is marked as “weak”. Delete the word weak on the table view declaration.
• You’re setting the table view to nil at some point on accident.
• The tableview isn’t the only thing nil: The drawer VC class reference is as well, resulting in no code running. This could be due to not properly finding the VC in the hierarchy, missing storing a reference somewhere, or it being deallocated when not in the window hierarchy. 

Note: Calling begin/end updates before/after reloadData is pointless, and may cause issues on the future. I recommend removing those calls.

However, this issue is not related to Pulley itself and is outside the scope of support I can provide. Other than the above troubleshooting tips, I won’t be able to assist further.

**Comment by pawangiri** [comment]
@brendan09 thanks for getting back. Appreciate the help. 
I see a drawer behaviour but not sure why. The drawer creates a new instance and therefore the reference to tabelView turns nil. This also happens in the demo app. 

Thoughts?

**Comment by brendan09** [comment]
> The drawer creates a new instance and therefore the reference to tabelView turns nil. 

The drawer doesn't have the ability to create new instances of your view controllers. If you're seeing that behavior, it's a result of your creating a new PulleyViewController instance and initializing it with new view controllers, or changing the view controllers on the existing view controller instance.

The sample app in the repo doesn't have an issue where the tableview becomes nil.
