### ISSUE TITLE
CABasicAnimation causes crash

### ISSUE THREAD

**Issue by sadanro100** [52inc/Pulley#243]
While testing animating the shadow for a UIView on PrimaryViewController with CABasicAnimation, I noticed if I tap the close button on my drawer viewcontroller twice, which triggers pulley's setPosition .closed, makes PulleyPassthroughScrollView.swift crash at line 27:

return touchDelegate.viewToReceiveTouch(scrollView: self, point: point).hitTest(touchDelegate.viewToReceiveTouch(scrollView: self, point: point).convert(point, from: self), with: event)

with "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFType doubleValue]: unrecognized selector sent to instance"

**Comment by brendan09** [comment]
This error is because something is being deallocated before this line is run the second time. This often occurs during animations, especially when they’re stacked. It can also occur when views are added or removed from the hierarchy as a result of a button press.

This isn’t something that can be fixed in Pulley, as it isn’t a detectable condition (or a flaw in the Pulley code itself). This is a memory management flaw caused by usage. You’ll need to ensure you prevent users from double pressing the button if code you’re running is subject to memory / deallocation / double free errors.

**Comment by sadanro100** [comment]
Thanks for clarifying, I'll prevent double taps.
