### ISSUE TITLE
how do you access the IBOutlets in PulleyViewController when its in the framework

### ISSUE THREAD

**Issue by MadeByDouglas** [52inc/Pulley#259]
I see in the example you connect IBOutlets to use Pulley in a storyboard. However, we don't subclass this, and if I just have embedded the framework, the PulleyViewController.swift is not accessible. So how would I connect the outlet to the storyboard?

**Comment by brendan09** [comment]
You need to change the class in Interface Builder to PulleyViewController.

**Comment by brendan09** [comment]
When you right click on the view controller that's highlighted in the IB sidebar, what do you see in the outlets list? It should list the outlets for Pulley if the framework is imported correctly.

Depending on your project configuration, you may need to do one of the following:

* Create an Objective-C bridging header and import Pulley in it.
* Use "Inherit Module From Target" instead of specifying the Pulley module.

As a note, the framework entry in Pulley exists for Carthage installs. I'm not sure about the details of using it manually. I generally recommend CocoaPods, or a manual inclusion of Pulley (just add the files to your project) rather than trying to keep a compiled framework current with Swift (it can cause major issues between Xcode versions). You can also utilize Carthage, but it has some of the same downsides.

**Comment by MadeByDouglas** [comment]
I see. No I don’t see the outlets, just generic new referencing outlet. I’m using Carthage. Hmm let me see if those suggestions help.

**Comment by MadeByDouglas** [comment]
well I ended up just doing it programmatically

**Comment by brendan09** [comment]
Hmm. That's interesting. It's odd that it would work programmatically, but Interface Builder wouldn't pickup on the outlets from the framework.

**Comment by MadeByDouglas** [comment]
Yeah im not sure

**Comment by samkhawase** [comment]
I had the same issue as well. I am using Carthage, and tried the Bridging-Header method, but that didn't work.
I solved it by doing it programmatically like @MadeByDouglas recommended.

**Comment by damianjsullivan** [comment]
FYI Known issue with Carthage and IBDesignable. 
https://github.com/Carthage/Carthage/issues/335

Workaround.
https://stackoverflow.com/questions/29933691/ibdesignable-from-external-framework

**Comment by jaunruh** [comment]
@MadeByDouglas i am having the same issue. I am using Carthage and added Pulley as a binary. But when setting the class in the Storyboard it doesn't even find the PulleyViewController. So when using the Assistent Editor I am consequently not able to connect the UIViews to the Outlets.

Any chance you can let me know how you solved this programmatically?

**Comment by MadeByDouglas** [comment]
Sorry, I never figured out the storyboard issues, I have it written entirely programmatic without storyboard to get it to work, so no outlets to deal with.

**Comment by moiz212** [comment]
It is very simple you just need to right Click on Pully VC and check for outlets ,you must missing it ,if yes then control drag the oultets for primary and drawer to your container UIView
