### ISSUE TITLE
Empty space on the right side

### ISSUE THREAD

**Issue by Matiaz** [52inc/Pulley#272]
Hi, first of all, thanks for the library, very cool, just have a problem with it, I keep getting this empty space on the right side, looks like the main view of the controller gets the full side if the window, but the inner view gets a space between itself and the controller's window, any ideas ? Also, is it possible to get the drawer over the tabbar ? thanks in advance

![img_0109](https://user-images.githubusercontent.com/757195/46576286-5c39f100-c983-11e8-9c4d-61ee76358307.PNG)

**Comment by brendan09** [comment]
The drawer view controller also gets equal width. If you’re seeing this behavior in the sample project, too, let me know and we’ll get it fixed. Otherwise it’s likely an issue with your constraints in your drawer view controller. 

You can use the tab bar controller as your primary content view controller if you want it to be behind it.
