### ISSUE TITLE
Drawer mask is wrong on landscape

### ISSUE THREAD

**Issue by zntfdr** [52inc/Pulley#284]
Hi all, 
I've changed [line 43 of the PrimaryContentViewController](https://github.com/52inc/Pulley/blob/master/Pulley/PrimaryContentViewController.swift#L43) in the sample app to always display the drawer layout. 

When I'm in landscape and the drawer is at the maximum extensions, this happens:
![img_3512](https://user-images.githubusercontent.com/5277837/47502139-3ff9e780-d891-11e8-9271-50027bf5b9f1.PNG).

This happens on iPhone X. Any help is much appreciated :)

**Comment by brendan09** [comment]
Yes, that’s expected behavior and in line with that setting. That setting controls the side drawer mode vs bottom drawer. On iPhone X, it insets the drawer from the notch so that nothing is below the notch. In order to keep the drawer centered, it’s inset from both sides. There isn’t a customization option for that behavior.

You can try it on an iPhone without a notch and it’ll go full width.

**Comment by zntfdr** [comment]
I'm sorry but I'm confused from your explanation: 
can you please let me know how to correct the mask position on a notch device with the drawer option?

**Comment by brendan09** [comment]
Are you using the latest version of Pulley? It has some fixes for mask positioning. If you’re using the latest version, that’s a bug that needs to be fixed in pulley itself.

**Comment by zntfdr** [comment]
Yes, I'm using the latest version: I did a clone of `master` just to open this issue 😅

**Comment by zntfdr** [comment]
>Ok, I’ll have someone take a look over the weekend. Thanks for reporting!

@brendan09 awesome! Thank you very much 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zntfdr** [comment]
I confirm the latest releases fixes the issue, many thanks! 👍
