### ISSUE TITLE
How to align drawerViewController top to navigation bar bottom?

### ISSUE THREAD

**Issue by bizibizi** [52inc/Pulley#286]

**Comment by bizibizi** [comment]
@brendan09 can you tell me please which property? i see several, but there is no one which will stick to NV sizes, right?

**Comment by brendan09** [comment]
The property is ‘drawerTopInset’. It won’t automatically track a navigation controller unless the navigation controller contains Pulley (rather than Pulley containing the navigation controller) and isTranslucent = false.

If you’re using it in another way, you need to manually update that property anytime your viewcontroller’s viewDidLayoutSubviews is called.

**Comment by bizibizi** [comment]
@brendan09 okay, i see. thank you! And is it possibel to remove 20px extra top spacing by code?

**Comment by brendan09** [comment]
The extra 20pt at the top is accounting for the safe area. (Status bar / navigation bar). On iOS < 11 it uses the topLayoutGuide of the PulleyViewController, on iOS 11+ it uses safe areas provided to Pulley. 

If you’re manually assigning the top inset, subtract out either the pulley topLayoutGuide or too safe area value depending on the version or iOS.
