### ISSUE TITLE
PulleyPassthroughScrollView close area

### ISSUE THREAD

**Issue by mihailsalari** [52inc/Pulley#328]
Hi, 
I have added in project a passcode lock and I set at start pulley to closed, but after dismiss of passcode controller, the PulleyPassthroughScrollView and few subviews are blocking my UI.
![Screen Shot 2019-03-31 at 4 06 19 AM](https://user-images.githubusercontent.com/23311250/55283399-0317ac80-536b-11e9-9c5a-2411c94ca7e6.png)

How to dismiss them?

Please see attached screenshot.

Regards,
Mike

**Comment by brendan09** [comment]
Hiding the drawer does not remove PulleyViewController from your view hierarchy because it’s managing the visibility of the primary content view controller. Your primary content view controller is embedded in PulleyViewController. 

The pass through scrollview is safe to leave, if you want PulleyViewController to remain in the hierarchy as it just proxies touches transparently though itself. It won’t block touches. 

It doesn’t sound like you’re modally presenting PulleyViewController, so it isn’t something you can just dismiss. 

If you can provide more info on how you’re using pulley (show/hide, etc). I can provide more info.

**Comment by mihailsalari** [comment]
Hi @brendan09 , you right, I presented pulley modally. Now I want to get rid of this scrollview or override to touches... I'll try and I'll come back... Thank you!

**Comment by brendan09** [comment]
If you presented Pulley modally, make sure you call dismiss on Pulley directly, not on your drawer or primary content VC.

**Comment by mihailsalari** [comment]
Ok, the variant with dismiss failed. How about override touches? Where I need to override them and what I should specify inside of function?

**Comment by brendan09** [comment]
You don’t need to override touches. The pass through scrollview does that automatically.

My recommendation to you is not to modally present Pulley, or if you do make sure you modally dismiss PulleyViewController NOT the drawer or primary content view controller. If you correctly modally dismiss Pulley, the scrollview and sub views would’ve gone away.

**Comment by mihailsalari** [comment]
After Passcode screen I'm redirected to main controller which are contentViewController, I can't dismiss pulley because it's a part of UI. It should be closed here and called just when I need it. Do you have any other ideas?

**Comment by brendan09** [comment]
Okay, in this case you don’t need to present or dismiss Pulley. You can use it the same way as the README / sample project.

The scrollview isn’t blocking your touches and is critical to how Pulley works. As the name describes, it passes through touches to your content view controller automatically. 

You can’t remove the scrollview.

**Comment by mihailsalari** [comment]
I'll try, thank you!
