### ISSUE TITLE
It's hard to scroll down the PulleyViewController if there is a UITableView inside it

### ISSUE THREAD

**Issue by joeyps** [52inc/Pulley#33]
There are two use cases that cause it:
1. Scroll down the UITableView slowly. When reaches the top of UITableView, it will cause over scroll until you release your finger. I expected it will scroll the PulleyViewController instead, just like Apple Map.
2. Scroll down the UITableView quickly, it will cause UITableView bouncing, if you scroll down the UITableView again immediately, UITableView will bounce again, never scroll down the PulleyViewController.

May I know how to improve the nest scrolling behaviors? 
For the case 2, I could improve it by setting UITableView.isScrollEnabled as false when contentOffset <= 0. I don't know if it is a good idea, but it just works like Apple Map.

**Comment by blg-nb** [comment]
I have the problem only with an UIPageViewController.

Does somebody has any idea?

**Comment by brendan09** [comment]
Both of these are implementation details up to the view controller contained inside the drawer, and not something that directly affects PulleyViewController's implementation.

If you'd like behavior closer to Apple Maps on these edge cases, then you'll have to implement that yourself inside your drawer VC. In order to fix it then you'll likely need to override touch event handling / responder chain implementations. It's unlikely that you'll find a setting or config on the tableview / scrollview to fix the issue.

**Comment by joeyps** [comment]
You're right. I eventually implemented it on my own. Thank you.

**Comment by sirvon** [comment]
joeyps can you share it?

**Comment by gautier-gdx** [comment]
@speshiou can you share your solution with us?
