### ISSUE TITLE
manual install of pulleyLib no import UIKit

### ISSUE THREAD

**Issue by MadeByDouglas** [52inc/Pulley#335]
So on the UIViewController+PulleyViewController.swift file there is no `import UIKit` so it fails.
Am I missing something? I added it to fix it, but this seems like a silly oversight.

**Comment by brendan09** [comment]
Looks like the contributor that added that forgot an import. It does work in CocoaPods, but would definitely break in a manual install. 

You’re welcome to open a PR, or @ulmentflam can fix this when he gets a chance. 

I don’t have commit access to this repo anymore, but I’ll try to flag this to him since it’s an easy fix.

**Comment by ulmentflam** [comment]
@MadeByDouglas I just pushed a fix with the addition of `import UIKit` to master. This update will be included in the next release as well. Thanks for pointing it out!
