### ISSUE TITLE
App getting hang on iOS 14 using pulley

### ISSUE THREAD

**Issue by ambi1132** [52inc/Pulley#405]
App is getting hanged in iOS14(xcode 12), coming white blank screen as we are initialising the root view controller using pulley library.
Please help me to resolve this issue. Is any update required in pulley library for iOS 14 because in previously versions it was working fine.

**Comment by ulmentflam** [comment]
@ambi1132 I probably need to update the README, as iOS 14 has caused this common issue in the Pulley lib. The hanging issue should have been fixed in release [2.8.5](https://github.com/52inc/Pulley/releases/tag/2.8.5) and above. That being said, if you upgrade Pulley and you are still running into a feedback loop use [this](https://www.hackingwithswift.com/articles/59/debugging-auto-layout-feedback-loops) guide to debug the loop. If it is related the PulleyViewController please replicate the issue in the sample app and add to this issue as much information as possible on the feedback loop.
