### ISSUE TITLE
Bug with scrolling

### ISSUE THREAD

**Issue by fariz-siracli** [52inc/Pulley#59]
Hi guys. Very good lib. But i just realized one strange situation. If we put tableview to pulley then during scrolling rows are updating. 
Just change sample's code as following and you will see

func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 15
    }
    var i = 0
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let row = tableView.dequeueReusableCell(withIdentifier: "SampleCell", for: indexPath)
        row.detailTextLabel?.text = String(i)
        i += 1
        return row
    }
if tableview row count is more than 10 or 15 then rows may be duplicated even 3 or 4 times.

Thank you for attention.

**Comment by brendan09** [comment]
Unfortunately, this is a bug in your tableview implementation not in Pulley. Although Pulley uses a tableview in its demo, it is not a tableview library. You’ll need to explore what’s wrong with your tableview implementation, as it’s unrelated to Pulley.

Thanks

**Comment by fariz-siracli** [comment]
hi brendan. i don't have bug in my code. i checked it several times. Just open your sample application and paste the code i have written above and you will see what's happening. Every time when pulley scrolls up and down, tableview's 
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) 
function is calling and row's are updating. If you want i can send you my own code also. 
I understand that it's not tableview library but implementing this, tableview is not behaving correctly.

Thanks.

**Comment by brendan09** [comment]
I understand, and looking at your code snippet, it doesn’t work because that’s not how tableviews render cells. They recycle them at random, and refresh whenever they see fit. The order in which cellForRow is called isn’t defined, so you can’t rely on an external counter. You’ve thus far been relying on a side effect of how it happens to load cells on the initial load event. If you had enough cells to scroll around, you’d see that it would also be causing ordering issues.

You should only be getting the cell number from the index path and its section / row property. It is not possible or proper to have an accurate variable you increment every time cellForRow is called. It will not work properly.

So, as I mentioned, Pulley doesn’t interact with the tableview in any way and the issue is your tableview implementation. The code snippet you’ve posted is  flawed in its approach to how tableviews actually work. 

As much as I’d like to help with individual tableview issues, we’ve had to take a hard line on troubleshooting people’s tableview implementations because (between issues and emails) we’d spend a large amount of time troubleshooting non-Pulley-related code.

**Comment by fariz-siracli** [comment]
Thank you. But i don't implement external counter. It' was just an example. My actual code is following
       let cell = tableView.dequeueReusableCell(withIdentifier: "poiCell", for: indexPath)
       let selectedPoi = searchResultPois[indexPath.row] as Poi
       cell.textLabel?.text = selectedPoi.address?.mapPoint.name
        return cell
So am i doing anything wrong? I did same in other simple views containg tableview and that was allright.
Thank you for attention

**Comment by brendan09** [comment]
It’s expected that cellForRow may be called at anytime, and may be called by the tableview as a result of dragging the Pulley drawer. 

I don’t immediately see an issue with your code snippet, however there are many other factors in your datasource / delegate implementation that could contribute to what you’re seeing. 

As I mentioned, I’m not able to help with your specific tableview implementation. It’s almost certainly something to do with cell recycling, so it’d be worth doing some logging to find out what’s going wrong in your implementation.

**Comment by fariz-siracli** [comment]
Ok. Thanks a lot anyway.
