### ISSUE TITLE
supportedDrawerPositions issue

### ISSUE THREAD

**Issue by ruilunli** [52inc/Pulley#60]
Hi, thanks for sharing such useful library. 

I have found that when the I set the supported position without '.open', then the drawer UI will break and can not be dragged. Is this an issue?

**Comment by brendan09** [comment]
No, that’s correct behavior.

If you only give it “open” as an allowed position, there is no other allowed position that the user could drag it to.

You should provide an array of any positions you want the drawer to be able to stop at for that value.

If you want to set the drawer to a specific position (or a specific starting position), then there are properties on the Pulley VC that you can use to accomplish that.

**Comment by ruilunli** [comment]
Thanks, but I actually assign every position except '.open'

`  func partialRevealDrawerHeight() -> CGFloat
  {
    
    return view.frame.size.height/2
  }
  
  func supportedDrawerPositions() -> [PulleyPosition] {
    `

**Comment by brendan09** [comment]
Apologies. My mistake, I misread that.

So, I did manage to replicate your issue. However, it's not related to the fact that your 'supportedDrawerPositions' doesn't contain 'open'.

Rather, it's related to the fact that you're using _view.frame.size.height/2_ as the height for the partial reveal. Print out the number generated by that expression at the point in the view controller lifecycle that method is called. You'll see that it's a small number, because the full layout pass hasn't occurred yet. Because this number is smaller than the 'collapsed' drawer position, it essentially 'locks' the UI because the numbers don't make mathematical sense to Pulley. (Partial reveal _should_ be larger than collapsed, but your implementation is returning a smaller number since the full layout hasn't occurred yet.)

Because Pulley uses this value to determine the size of the drawer content VC, you won't be able to use the drawer content VC's 'view' property for the height. However, you can use the Pulley VC's height for the calculation, which will produce the same result:

`return parent!.view.bounds.height  / 2.0`

If you don't want to use a force unwrap (I know I wouldn't, even if should never crash), you can provide a default value this way:

`return (parent?.view.bounds.height ?? 568.0) / 2.0`

**Comment by ruilunli** [comment]
Thanks a lot, that solves my problem!

**Comment by brendan09** [comment]
Ok, great! I’m gonna go ahead and close this issue. Feel free to create another if you encounter any other problems.
