### ISSUE TITLE
iPhone X and Safe Areas

### ISSUE THREAD

**Issue by drewpitchford** [52inc/Pulley#74]
Will you be updating Pulley so that the drawer obeys the Safe Areas introduced in iOS 11? Most pressing is the bottom safe area (to avoid conflicts with the home indicator). But the leading and trailing safe areas should be used too. Right now, the "notch" covers part of the drawer in landscape on iPhone X.

**Comment by brendan09** [comment]
It is my intention to update Pulley to be compatible with iPhone X and safe areas. It may by a couple of weeks before I can get to it, but it should be at least a month before the X is released.

**Comment by funkenstrahlen** [comment]
Happy to hear that!

**Comment by brendan09** [comment]
@drewpitchford @funkenstrahlen  Swift 4 support, with full Safe Area / iPhone X support is now up on CocoaPods and on master. However, because it introduces support for Safe Areas, it is a breaking change that will require some small API changes. The README has some info on supporting Safe Areas, and the example project has been updated with the proper usage + comments.
