### ISSUE TITLE
mapView isn't properly initialized

### ISSUE THREAD

**Issue by kyleloyka** [52inc/Pulley#84]
mapView is nil when trying to access in PrimaryContentViewController's viewDidLoad()

**Comment by brendan09** [comment]
Looks like the IBOutlet was disconnected during refactoring of the sample project. Since the demo app doesn't access the MapView, it wasn't an issue in the demo app.

I've reconnected the IBOutlet and pushed a commit to master. You can now pull the repo with the fix if you want to start working in the sample app.

**Comment by brendan09** [comment]
@kyleloyka I'm going to close this issue now that it's resolved. Let me know if you have any issues.

**Comment by kyleloyka** [comment]
Thanks for the fast turn around, and for your work on this project. I've been teaching myself Swift and the iOS frameworks, and this project has been very helpful!
