### ISSUE TITLE
topInset appears set from top of screen, not Safe Area

### ISSUE THREAD

**Issue by skeeJay** [52inc/Pulley#86]
I know the topInset defaults to 50 (I'm not overriding it), but it appears on both iPhone 7 and iPhone X to be set relative to the screen (including the status bar) instead of the Safe Area. On iPhone X, the status bar is 44pt and only 6 additional pixels are revealed. Or am I doing something that overrides the Safe Area somehow? (This overcompensation towards the top of the screen seems to also cause the background of the drawer not to reach the _bottom_ of the screen.

![img_e77adc6da744-1](https://user-images.githubusercontent.com/506096/31051376-dfae1156-a634-11e7-946b-3cb5d5e3eb3e.jpeg)

![simulator screen shot - iphone x - 2017-09-30 at 23 02 09](https://user-images.githubusercontent.com/506096/31051377-dfb08c6a-a634-11e7-864b-d6ac2ad9da48.png)

**Comment by brendan09** [comment]
@skeeJay Make sure you’re using Pulley 2.0 on CocoaPods. It supports topInset from the safe area. In Pulley 2.0, the default top inset isn’t 50 anymore (it’s now 20), which is what makes me think you’re on an older version.

**Comment by skeeJay** [comment]
Gotcha. Adding `, '~> 2.0'` to the podfile fixed it. Should that be included in the CocoaPods instructions in the ReadMe? Took me a bit to realize I needed to add it myself.

**Comment by brendan09** [comment]
If you’re installing new, it would’ve grabbed the latest version (2.0). CocoaPods ‘locks’ the version of any pod to the version it was when you first install it. Since you first installed a previous version, you were ‘locked’ to that until you told CocoaPods to update. To update a pod, you can run ‘pod update <pod name>’. In this scenario, you could’ve updated Pulley from it’s ‘locked’ version by running ‘pod update Pulley’.

Adding the ~ 2.0 forced CocoaPods to update because you specified that the version _must_ be in the 2.0.x range. You’re welcome to keep this requirement if you’d like, but it will prevent you from being able to simply ‘pod update Pulley’ as new Pulley releases come out. (It will also prevent a general ‘pod update’ from updating Pulley)

Since this is a standard behavior / usage of CocoaPods, I don’t feel it should be added to the ReadMe. CocoaPods has it’s own documentation on how versioning works for dependencies, and so I don’t feel that Pulley needs it’s own duplicate CocoaPods documentation section.

**Comment by skeeJay** [comment]
You're right, `pod update` is the better solution. Sorry for my Cocoapods naïveté. Thanks for updating Pulley for iPhone X so quickly!

**Comment by brendan09** [comment]
No problem! I’m glad this fixed it for you! Let me know if you have any issues with Pulley 2.0 and safe areas. Make sure and check out the iOS 11 and safe areas section of the readme. There are some required delegate method changes you’ll need to make if you’re upgrading from Pulley 1.x.
