### ISSUE TITLE
Fully expended size api

### ISSUE THREAD

**Issue by Alex293** [52inc/Pulley#9]
I think it would be better to set the full size the way we set collapsed and partial size to be more consistent. Tho, You may still keep the inset as a minimum distance or something like this.

**Comment by brendan09** [comment]
A few reasons I don't plan on doing this:

1. Unlike the collapsed / partial sizes, I need to know the full screen height ahead of time in order to compute the contentSize of the scrollView. If it changes, then I need to recompute the scrollView contentSize and layout. This prohibits delegation in any meaningful way. In addition, it isn't something likely to change per view controller.

2. Because the intention of the 'full screen' size is to be full screen. In order to support various device sizes people would need to do their own "how big is full screen and how much distance from the top do I want?" math. That's a higher burden of usage than I would like.

3. Backwards compatibility with people currently using the library. Right now people are using the inset property. A competing ability like you mentioned would not be optimal. So, I would have to pick one or the other. I do prefer the current way, and I don't want to affect backwards compatibility.

As a result, I won't be adding a "height" setting for the full screen state. I also don't recommend trying to create a "height" for fullscreen do to various device sizes.

I do plan on implementing the ability to disable fullscreen, but that will come in the form of a separate API.

**Comment by Alex293** [comment]
Okay i can understand this. If someone need the functionality i wanted this is how i did it : 
let mapEventPreviewDrawerCompleteInset : CGFloat = UIScreen.main.nativeBounds.height - sizeIWant
