### ISSUE TITLE
Not dismissing from memory

### ISSUE THREAD

**Issue by mukulm24** [52inc/Pulley#91]
When i dismiss the pulleycontroller from the view then the content view controller is still in memory and when i present pulleycontroller, the older instance is still running of the content view controller.

**Comment by brendan09** [comment]
It sounds like you might have a retain cycle in your content view controller, unrelated to Pulley itself.

This can be caused by:

* Capturing self in a block without explicitly capturing it as weak.
* Having a delegate pattern that doesn't use a weak variable as the delegate.
* If your keeping a reference to Pulley as a variable in your content view controller or drawer view controller.
* If you're keeping a variable referencing the Pulley controller.

You can use Xcodes memory graph to determine what is holding Pulley and/or your content view controller in memory. You're welcome to post a picture of the memory graph here. Please click on the link keeping Pulley in memory and have the right side bar open for detail in the screenshot.
